# Stany aplikacji - wartości tekstowe
BEZCZYNNOSC = "BEZCZYNNOSC"
DETEKCJA = "DETEKCJA"
DETEKCJA_PONOWNA = "DETEKCJA_PONOWNA"
OCZEKIWANIE_POMIAR = "OCZEKIWANIE_POMIAR"
POMIAR = "POMIAR"
PONOW_POMIAR = "PONOW_POMIAR"
PIN_NIEUDANY_WYBOR = "PIN_NIEUDANY_WYBOR"
KALIBRACJA_MQ3 = "KALIBRACJA_MQ3"
